### ISSUE TITLE
Deprecated function EE_Fieldtype() in EE 2.6+

### ISSUE THREAD

**Issue by ryanjbonnell** [monooso/dropdate.ee_addon#7]
Using DropDate v2.20 and EE 2.7.0 (build 20130827) with PHP v5.3.24, I get the following notices in the Developer Log:

```
Deprecated function EE_Fieldtype() called in system/expressionengine/third_party/dropdate/ft.dropdate.php on line 50.

From template tag exp:playa:parents in events/details.

Deprecated since 2.6. Use EE_Fieldtype::__construct() instead.
```

This is more of a community service message than a bug _per se_, as the DropDate Fieldtype still works with EE 2.6—2.7, but fails in EE 2.8+.

**Comment by stevegrossi** [comment]
This now causes installation to fail for me in EE 2.8 (build 20140228):

```
Fatal error: Call to undefined method EE_Fieldtype::EE_Fieldtype()
```

**Comment by stevegrossi** [comment]
It's a simple patch for anyone else having this issue. Just replace line 50 in ft.dropdate.php:

```
parent::EE_Fieldtype();
```

with

```
parent::__construct();
```

**Comment by pierrebayartz** [comment]
Having the same error here. Would be nice if the patch from @stevegrossi would be implemented in the next version of dropdate.

Greets

**Comment by monooso** [comment]
This project is no longer maintained, primarily because I no longer do any work with ExpressionEngine. If somebody wants to submit a patch, I'm happy to merge it.
